# Generated by Django 3.2.9 on 2021-11-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='description',
            field=models.TextField(default=None, null=True, verbose_name='个性签名'),
        ),
    ]
