# Generated by Django 3.2.9 on 2021-11-22 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(max_length=255, verbose_name='家庭地址')),
                ('student', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='info', to='student.student')),
            ],
            options={
                'verbose_name': '学生信息表',
                'verbose_name_plural': '学生信息表',
                'db_table': 'tb_student_info',
            },
        ),
    ]
