# Generated by Django 3.2.9 on 2021-11-23 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20211123_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='成绩')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='score_list', to='student.student')),
            ],
            options={
                'verbose_name': '学生成绩表',
                'verbose_name_plural': '学生成绩表',
                'db_table': 'tb_achievement',
            },
        ),
    ]
