# Generated by Django 3.2.9 on 2021-11-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_achievement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='老师')),
            ],
            options={
                'verbose_name': '老师信息表',
                'verbose_name_plural': '老师信息表',
                'db_table': 'tb_teacher',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='课程')),
                ('teacher_list', models.ManyToManyField(related_name='course_list', to='student.Teacher')),
            ],
            options={
                'verbose_name': '老师信息表',
                'verbose_name_plural': '老师信息表',
                'db_table': 'tb_course',
            },
        ),
    ]
